<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc70febe1fc4410c215b501c0b544ce0e
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'N' => 
        array (
            'Notification\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Notification\\' => 
        array (
            0 => __DIR__ . '/../..' . '/_app',
        ),
    );

    public static $classMap = array (
        'Notification\\Email' => __DIR__ . '/../..' . '/_app/Email.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc70febe1fc4410c215b501c0b544ce0e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc70febe1fc4410c215b501c0b544ce0e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc70febe1fc4410c215b501c0b544ce0e::$classMap;

        }, null, ClassLoader::class);
    }
}
